### ISSUE TITLE
Release v0.1.0

### ISSUE THREAD

**Issue by chaspy** [kamontia/qs#33]
# Feature
- [x] #11 Add the option to suppress logging
- [x] #17 Aggregate commit messages into one
- [x] #25 Make commit number two digit

# Improvement
- [x] #19 Download dependent packages from the current branch
- [x] #34 Validation argument
- [x] #28 Error handling by hard reset
- [x] #35 Prepare flag for test is not worked
- [x] #42 Fix the log message
- [x] #40 Refactor test script

# Document
- [x] #45 Update Document for v0.1.0
- [x] #48 Add demo movie in README
- [x] #53 Set License
- [x] #55 Issue Template

# Release
- [x] tag [v0.1.0](https://github.com/kamontia/qs/tree/v0.1.0)
- [x] release [v0.1.0](https://github.com/kamontia/qs/releases/tag/v0.1.0)
- [x] download & run at any platform
  - [x] linux(ubuntu)
  - [x] windows
  - [x] os x

# After Release
- [ ] #13 modify author and committer on git hub log
- [x] Dog fooding

# Article
- [x] @kamontia [最速でgit-rebaseするコマンドqs(quick squash)を作ってみた](https://qiita.com/kamontia/items/ac5c7f99599049b545e9)
- [x] @chaspy [複数のコミットをsquashするコマンド「qs(quick squash)」を作った](http://blog.chaspy.me/entry/2018/08/26/120000)

**Comment by chaspy** [comment]
🎉
